"""LLM report generation via RAG — synthesizes comprehensive botanical reports.

Supports multiple LLM providers (Gemini, Claude, OpenAI, Llama) to synthesize
reports from:
    - Model inference outputs (species + pathology)
    - Vrikshayurveda Dosha mapping
    - Retrieved passages from Ayurvedic texts (RAG context)

Report structure:
    1. Authenticated botanical identity (species, family, Sanskrit/common names)
    2. Classical medicinal properties (Rasa, Guna, Virya, Vipaka)
    3. Current health status and pathology diagnosis
    4. Vrikshayurveda Dosha assessment
    5. Traditional therapeutic intervention
    6. Procurement quality assessment
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass

from phytoveda.llm.providers import BaseLLM, get_provider
from phytoveda.rag.retriever import RetrievalResult
from phytoveda.vrikshayurveda.mapper import DoshaAssessment


@dataclass
class BotanicalReport:
    """Comprehensive botanical report generated by RAG + LLM."""

    species_name: str
    species_family: str
    sanskrit_name: str
    common_names: list[str]
    rasa: str  # Taste
    guna: str  # Qualities
    virya: str  # Potency
    vipaka: str  # Post-digestive effect
    health_status: str
    pathology_diagnosis: str
    dosha_assessment: str
    treatments: list[str]
    procurement_quality: str  # Suitable / Not suitable / Conditional
    full_report_text: str

    def to_json(self) -> str:
        """Serialize report to JSON string."""
        return json.dumps(asdict(self), indent=2, ensure_ascii=False)

    def to_markdown(self) -> str:
        """Format report as human-readable Markdown."""
        treatments_md = "\n".join(f"- {t}" for t in self.treatments)
        common_md = ", ".join(self.common_names) if self.common_names else "N/A"

        return f"""# Botanical Report: {self.species_name}

## 1. Authenticated Botanical Identity
- **Scientific Name**: {self.species_name}
- **Family**: {self.species_family}
- **Sanskrit Name**: {self.sanskrit_name}
- **Common Names**: {common_md}

## 2. Classical Medicinal Properties (Rasa-Guna-Virya-Vipaka)
- **Rasa (Taste)**: {self.rasa}
- **Guna (Qualities)**: {self.guna}
- **Virya (Potency)**: {self.virya}
- **Vipaka (Post-digestive Effect)**: {self.vipaka}

## 3. Current Health Status
- **Diagnosis**: {self.pathology_diagnosis}
- **Health Status**: {self.health_status}

## 4. Vrikshayurveda Dosha Assessment
{self.dosha_assessment}

## 5. Traditional Therapeutic Intervention
{treatments_md}

## 6. Procurement Quality Assessment
**{self.procurement_quality}**

---

{self.full_report_text}
"""


REPORT_SYSTEM_PROMPT = """\
You are an expert Ayurvedic botanist and pharmacognosist with deep knowledge of:
- Classical Ayurvedic texts (Charaka Samhita, Susruta Samhita, Vrikshayurveda)
- Medicinal plant identification and pharmacological properties
- The Rasa-Guna-Virya-Vipaka system of drug classification
- Vrikshayurveda Tridosha framework for plant pathology

You will receive a plant diagnosis from an AI vision system along with relevant passages
from Ayurvedic texts. Generate a comprehensive botanical report following the exact
structure requested. Be precise and cite classical texts where possible. If information
is not available in the provided context, clearly state so rather than speculating.
"""


def build_report_prompt(
    species_name: str,
    pathology_label: str,
    dosha: DoshaAssessment,
    retrieved_contexts: list[RetrievalResult],
    confidence: float = 0.0,
) -> str:
    """Build the user prompt for LLM report generation.

    Combines model outputs and retrieved RAG contexts into a structured prompt.
    """
    # Format retrieved contexts
    context_sections = []
    for i, ctx in enumerate(retrieved_contexts, 1):
        context_sections.append(
            f"[Source {i}: {ctx.source}, {ctx.chapter}]\n{ctx.text}"
        )
    contexts_text = (
        "\n\n".join(context_sections)
        if context_sections
        else "No retrieved contexts available."
    )

    # Format Dosha assessment
    symptoms = "; ".join(dosha.classical_symptoms[:3]) if dosha.classical_symptoms else "N/A"
    treatments = "; ".join(dosha.treatments[:3]) if dosha.treatments else "N/A"

    return f"""\
## AI Vision System Diagnosis

- **Species**: {species_name}
- **Pathology**: {pathology_label}
- **Model Confidence**: {confidence:.1%}
- **Vrikshayurveda Dosha**: {dosha.dosha.value}
- **Classical Symptoms**: {symptoms}
- **Recommended Treatments**: {treatments}

## Retrieved Ayurvedic Text Passages

{contexts_text}

## Instructions

Based on the AI diagnosis and the retrieved classical text passages, generate a
comprehensive botanical report with the following sections. Return your response
as valid JSON with these exact keys:

{{
    "species_family": "botanical family",
    "sanskrit_name": "Sanskrit name of the plant",
    "common_names": ["list", "of", "common", "names"],
    "rasa": "taste classification",
    "guna": "quality classification",
    "virya": "potency classification",
    "vipaka": "post-digestive effect",
    "health_status": "brief health status summary",
    "dosha_assessment": "detailed Dosha assessment paragraph",
    "procurement_quality": "Suitable / Not suitable / Conditional with explanation",
    "full_report_text": "comprehensive narrative report (2-3 paragraphs)"
}}
"""


class ReportGenerator:
    """Generate comprehensive botanical reports using RAG + LLM.

    Supports multiple LLM providers: Gemini, Claude, OpenAI, and Llama.

    Usage:
        # Default: Gemini
        generator = ReportGenerator(provider="gemini", api_key="...")

        # Claude
        generator = ReportGenerator(provider="claude", api_key="sk-ant-...")

        # OpenAI
        generator = ReportGenerator(provider="openai", api_key="sk-...")

        # Llama (local via Ollama)
        generator = ReportGenerator(provider="llama")

        report = generator.generate(
            species_name="Azadirachta indica",
            pathology_label="Bacterial Spot",
            dosha=dosha_assessment,
            retrieved_contexts=retrieval_results,
        )
    """

    def __init__(
        self,
        provider: str = "gemini",
        model_name: str | None = None,
        api_key: str | None = None,
        base_url: str | None = None,
        llm: BaseLLM | None = None,
    ) -> None:
        self._provider_name = provider
        self._model_name = model_name
        self._api_key = api_key
        self._base_url = base_url
        self._llm = llm  # Allow injecting a pre-configured provider

    def _get_llm(self) -> BaseLLM:
        """Lazily initialize the LLM provider."""
        if self._llm is None:
            self._llm = get_provider(
                provider=self._provider_name,
                model_name=self._model_name,
                api_key=self._api_key,
                base_url=self._base_url,
                temperature=0.3,
                max_tokens=2048,
            )
        return self._llm

    def generate(
        self,
        species_name: str,
        pathology_label: str,
        dosha: DoshaAssessment,
        retrieved_contexts: list[RetrievalResult] | None = None,
        confidence: float = 0.0,
    ) -> BotanicalReport:
        """Generate a comprehensive botanical report via LLM.

        Args:
            species_name: Predicted species name.
            pathology_label: Predicted pathology class.
            dosha: Vrikshayurveda Dosha assessment from the mapper.
            retrieved_contexts: RAG-retrieved passages from Ayurvedic texts.
            confidence: Model confidence score.

        Returns:
            Structured BotanicalReport.

        Raises:
            RuntimeError: If LLM response cannot be parsed.
        """
        contexts = retrieved_contexts or []
        prompt = build_report_prompt(
            species_name, pathology_label, dosha, contexts, confidence
        )

        llm = self._get_llm()
        response_text = llm.generate(REPORT_SYSTEM_PROMPT, prompt)

        return self._parse_response(species_name, pathology_label, dosha, response_text)

    def generate_offline(
        self,
        species_name: str,
        pathology_label: str,
        dosha: DoshaAssessment,
    ) -> BotanicalReport:
        """Generate a report without LLM — uses only Dosha mapping data.

        Useful for offline/testing scenarios where the Gemini API is unavailable.
        """
        health = "Healthy" if pathology_label == "Healthy" else f"Affected: {pathology_label}"

        if pathology_label == "Healthy":
            procurement = "Suitable — specimen shows no signs of disease or imbalance"
        else:
            procurement = (
                f"Conditional — specimen shows {dosha.dosha.value} imbalance "
                f"({pathology_label}). Treatment required before pharmaceutical use."
            )

        return BotanicalReport(
            species_name=species_name,
            species_family="",
            sanskrit_name="",
            common_names=[],
            rasa="",
            guna="",
            virya="",
            vipaka="",
            health_status=health,
            pathology_diagnosis=pathology_label,
            dosha_assessment=f"{dosha.dosha.value} — confidence {dosha.confidence:.1%}",
            treatments=dosha.treatments,
            procurement_quality=procurement,
            full_report_text=(
                f"AI vision system identified {species_name} with {pathology_label}. "
                f"Vrikshayurveda classification: {dosha.dosha.value}. "
                f"Classical symptoms: {'; '.join(dosha.classical_symptoms[:2])}. "
                f"RAG context unavailable — report generated from Dosha mapping only."
            ),
        )

    def _parse_response(
        self,
        species_name: str,
        pathology_label: str,
        dosha: DoshaAssessment,
        response_text: str,
    ) -> BotanicalReport:
        """Parse LLM JSON response into a BotanicalReport."""
        try:
            data = json.loads(response_text)
        except json.JSONDecodeError as e:
            raise RuntimeError(f"Failed to parse LLM response as JSON: {e}") from e

        return BotanicalReport(
            species_name=species_name,
            species_family=data.get("species_family", ""),
            sanskrit_name=data.get("sanskrit_name", ""),
            common_names=data.get("common_names", []),
            rasa=data.get("rasa", ""),
            guna=data.get("guna", ""),
            virya=data.get("virya", ""),
            vipaka=data.get("vipaka", ""),
            health_status=data.get("health_status", ""),
            pathology_diagnosis=pathology_label,
            dosha_assessment=data.get("dosha_assessment", dosha.dosha.value),
            treatments=dosha.treatments,
            procurement_quality=data.get("procurement_quality", ""),
            full_report_text=data.get("full_report_text", ""),
        )
